apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: log-service
spec:
  template:
    spec:
      containerConcurrency: 50
      containers:
        - image: bedirhangull/hrcubo-log-service:0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
          env:
            - name: DB_HOST
              value: mongodb
            - name: DB_PORT
              value: "27017"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: DB_NAME
              value: admin